import { Humanology } from '../types';

export const INTERTYPES: Record<Humanology.Intertype, Humanology.IntertypeProp> = {
    ENTP: {
        element: 'air',
        role: 'knight',
        alias: 'Дон Кихот',
        mindKey: 'irrational-1',
        mind: 'casual',
        name: 'Новатор',
        gender: 'male',
        club: 'scientific',
        tarot: 'swords', // масть
        psychotype: 'infantile', // группа
        populationPercentage: '2 — 5%',
        aspects: {
            good: 'ideas',
            necessary: 'logic',
            bad: 'time',
            noNeed: 'business',
            fear: 'will',
            problems: 'people',
            desires: 'comfort',
            solutions: 'emotions',
        },
        stimulant: 'uniqueness',
        communication: 'business',
        companion: 'categorical',
        temperament: 'sanguine',
        ideology: 'chaoticNeutral',
        jungs: [
            'intuit',
            'logic',
            'extravert',
            'irrational',
        ],
        reinin: [
            'static',
            'positivist',
            'questim',
            'tactician',
            'constructivist',

            'process',
            'compliant',
            'careless',

            'reasonable',
            'subjective',
            'democrat',
        ],
    },

    ISFP: {
        element: 'air',
        role: 'lady',
        alias: 'Дюма',
        mindKey: 'irrational-2',
        mind: 'algorithmic',
        name: 'Дипломат',
        gender: 'female',
        club: 'social',
        tarot: 'cups', // масть
        psychotype: 'care', // группа
        populationPercentage: '5 — 9%',
        aspects: {
            good: 'comfort',
            necessary: 'emotions',
            bad: 'will',
            noNeed: 'people',
            fear: 'time',
            problems: 'business',
            desires: 'ideas',
            solutions: 'logic',
        },
        stimulant: 'welfare',
        communication: 'sincere',
        companion: 'sensitive',
        temperament: 'melancholic',
        ideology: 'chaoticKindly',
        jungs: [
            'sensoric',
            'etic',
            'introvert',
            'irrational',
        ],
        reinin: [
            'dynamic',
            'negativist',
            'declamtim',
            'strategist',
            'emotivist',

            'result',
            'compliant',
            'careless',

            'reasonable',
            'subjective',
            'democrat',
        ],
    },

    ESFJ: {
        element: 'air',
        role: 'queen',
        alias: 'Гюго',
        mindKey: 'rational-4',
        mind: 'vortical',
        name: 'Энтузиаст',
        gender: 'female',
        club: 'social',
        tarot: 'wands', // масть
        psychotype: 'care', // группа
        populationPercentage: '9 — 13%',
        aspects: {
            good: 'emotions',
            necessary: 'comfort',
            bad: 'people',
            noNeed: 'will',
            fear: 'business',
            problems: 'time',
            desires: 'logic',
            solutions: 'ideas',
        },
        stimulant: 'status',
        communication: 'passionate',
        companion: 'uncompromising',
        temperament: 'choleric',
        ideology: 'chaoticKindly',
        jungs: [
            'sensoric',
            'etic',
            'extravert',
            'rational',
        ],
        reinin: [
            'dynamic',
            'positivist',
            'declamtim',
            'tactician',
            'constructivist',

            'result',
            'stubborn',
            'provident',

            'reasonable',
            'subjective',
            'democrat',
        ],
    },

    INTJ: {
        element: 'air',
        role: 'paige',
        alias: 'Робеспьер',
        mindKey: 'rational-1',
        mind: 'holographic',
        name: 'Аналитик',
        gender: 'male',
        club: 'scientific',
        tarot: 'pentacles', // масть
        psychotype: 'infantile', // группа
        populationPercentage: '2 — 4%',
        aspects: {
            good: 'logic',
            necessary: 'ideas',
            bad: 'business',
            noNeed: 'time',
            fear: 'people',
            problems: 'will',
            desires: 'emotions',
            solutions: 'comfort',
        },
        stimulant: 'selfSufficiency',
        communication: 'coldBlooded',
        companion: 'restrained',
        temperament: 'phlegmatic',
        ideology: 'lawAbidingNeutral',
        jungs: [
            'intuit',
            'logic',
            'introvert',
            'irrational',
        ],
        reinin: [
            'static',
            'negativist',
            'questim',
            'strategist',
            'emotivist',

            'result',
            'stubborn',
            'provident',

            'reasonable',
            'subjective',
            'democrat',
        ],
    },

    ISTJ: {
        element: 'fire',
        role: 'lady',
        alias: 'Максим Горький',
        mindKey: 'rational-4',
        mind: 'casual',
        name: 'Инспектор',
        gender: 'female',
        club: 'practice',
        tarot: 'pentacles', // масть
        psychotype: 'aggressor', // группа
        populationPercentage: '11 — 14%',
        aspects: {
            good: 'logic',
            necessary: 'will',
            bad: 'business',
            noNeed: 'comfort',
            fear: 'people',
            problems: 'ideas',
            desires: 'emotions',
            solutions: 'time',
        },
        stimulant: 'welfare',
        communication: 'coldBlooded',
        companion: 'sensitive',
        temperament: 'phlegmatic',
        ideology: 'lawAbidingBad',
        jungs: [
            'sensoric',
            'logic',
            'introvert',
            'rational',
        ],
        reinin: [
            'static',
            'positivist',
            'declamtim',
            'tactician',
            'emotivist',

            'result',
            'stubborn',
            'careless',

            'decisive',
            'subjective',
            'aristocrat',
        ],
    },

    ENFJ: {
        element: 'fire',
        role: 'knight',
        alias: 'Гамлет',
        mindKey: 'rational-1',
        mind: 'algorithmic',
        name: 'Наставник',
        gender: 'male',
        club: 'humanitarian',
        tarot: 'wands', // масть
        psychotype: 'victim', // группа
        populationPercentage: '2 — 5%',
        aspects: {
            good: 'emotions',
            necessary: 'time',
            bad: 'people',
            noNeed: 'ideas',
            fear: 'business',
            problems: 'comfort',
            desires: 'logic',
            solutions: 'will',
        },
        stimulant: 'uniqueness',
        communication: 'passionate',
        companion: 'categorical',
        temperament: 'choleric',
        ideology: 'chaoticBad',
        jungs: [
            'intuit',
            'etic',
            'extravert',
            'rational',
        ],
        reinin: [
            'dynamic',
            'negativist',
            'questim',
            'strategist',
            'constructivist',

            'process',
            'stubborn',
            'careless',

            'decisive',
            'subjective',
            'aristocrat',
        ],
    },

    INFP: {
        element: 'fire',
        role: 'paige',
        alias: 'Есенин',
        mindKey: 'irrational-1',
        mind: 'vortical',
        name: 'Лирик',
        gender: 'female',
        club: 'humanitarian',
        tarot: 'cups', // масть
        psychotype: 'victim', // группа
        populationPercentage: '4 — 5%',
        aspects: {
            good: 'time',
            necessary: 'emotions',
            bad: 'ideas',
            noNeed: 'people',
            fear: 'comfort',
            problems: 'business',
            desires: 'will',
            solutions: 'logic',
        },
        stimulant: 'selfSufficiency',
        communication: 'sincere',
        companion: 'provident',
        temperament: 'melancholic',
        ideology: 'chaoticNeutral',
        jungs: [
            'intuit',
            'etic',
            'introvert',
            'irrational',
        ],
        reinin: [
            'dynamic',
            'positivist',
            'questim',
            'tactician',
            'emotivist',

            'result',
            'compliant',
            'provident',

            'decisive',
            'subjective',
            'aristocrat',
        ],
    },

    ESTP: {
        element: 'fire',
        role: 'king',
        alias: 'Жуков',
        mindKey: 'irrational-1',
        mind: 'vortical',
        name: 'Лидер',
        gender: 'male',
        club: 'practice',
        tarot: 'swords', // масть
        psychotype: 'aggressor', // группа
        populationPercentage: '4 — 5%',
        aspects: {
            good: 'will',
            necessary: 'logic',
            bad: 'comfort',
            noNeed: 'business',
            fear: 'ideas',
            problems: 'people',
            desires: 'time',
            solutions: 'emotions',
        },
        stimulant: 'status',
        communication: 'business',
        companion: 'volitional',
        temperament: 'sanguine',
        ideology: 'chaoticKindly',
        jungs: [
            'sensoric',
            'logic',
            'extravert',
            'irrational',
        ],
        reinin: [
            'static',
            'negativist',
            'declamtim',
            'strategist',
            'constructivist',

            'result',
            'compliant',
            'provident',

            'decisive',
            'subjective',
            'aristocrat',
        ],
    },

    INTP: {
        element: 'water',
        role: 'paige',
        alias: 'Бальзак',
        mindKey: 'irrational-1',
        mind: 'algorithmic',
        name: 'Критик',
        gender: 'male',
        club: 'scientific',
        tarot: 'swords', // масть
        psychotype: 'victim', // группа
        populationPercentage: '3 — 5%',
        aspects: {
            good: 'time',
            necessary: 'business',
            bad: 'ideas',
            noNeed: 'logic',
            fear: 'comfort',
            problems: 'emotions',
            desires: 'will',
            solutions: 'people',
        },
        stimulant: 'selfSufficiency',
        communication: 'passionate',
        companion: 'provident',
        temperament: 'melancholic',
        ideology: 'neutral',
        jungs: [
            'intuit',
            'logic',
            'introvert',
            'irrational',
        ],
        reinin: [
            'dynamic',
            'negativist',
            'declamtim',
            'tactician',
            'constructivist',

            'process',
            'stubborn',
            'provident',

            'decisive',
            'objective',
            'democrat',
        ],
    },

    ESFP: {
        element: 'water',
        role: 'queen',
        alias: 'Наполеон',
        mindKey: 'irrational-2',
        mind: 'casual',
        name: 'Политик',
        gender: 'female',
        club: 'social',
        tarot: 'cups', // масть
        psychotype: 'aggressor', // группа
        populationPercentage: '4 — 9%',
        aspects: {
            good: 'will',
            necessary: 'people',
            bad: 'comfort',
            noNeed: 'emotions',
            fear: 'ideas',
            problems: 'logic',
            desires: 'time',
            solutions: 'business',
        },
        stimulant: 'status',
        communication: 'passionate',
        companion: 'volitional',
        temperament: 'sanguine',
        ideology: 'chaoticBad',
        jungs: [
            'sensoric',
            'etic',
            'extravert',
            'irrational',
        ],
        reinin: [
            'static',
            'positivist',
            'questim',
            'strategist',
            'emotivist',

            'process',
            'stubborn',
            'provident',

            'decisive',
            'objective',
            'democrat',
        ],
    },

    ISFJ: {
        element: 'water',
        role: 'lady',
        alias: 'Драйзер',
        mindKey: 'rational-4',
        mind: 'casual',
        name: 'Хранитель',
        gender: 'female',
        club: 'social',
        tarot: 'wands', // масть
        psychotype: 'aggressor', // группа
        populationPercentage: '9 — 14%',
        aspects: {
            good: 'people',
            necessary: 'will',
            bad: 'emotions',
            noNeed: 'comfort',
            fear: 'logic',
            problems: 'ideas',
            desires: 'business',
            solutions: 'time',
        },
        stimulant: 'welfare',
        communication: 'sincere',
        companion: 'sensitive',
        temperament: 'phlegmatic',
        ideology: 'lawAbidingBad',
        jungs: [
            'sensoric',
            'etic',
            'introvert',
            'rational',
        ],
        reinin: [
            'static',
            'negativist',
            'questim',
            'tactician',
            'constructivist',

            'result',
            'compliant',
            'provident',

            'decisive',
            'objective',
            'democrat',
        ],
    },

    ENTJ: {
        element: 'water',
        role: 'knight',
        alias: 'Джек Лондон',
        mindKey: 'rational-1',
        mind: 'vortical',
        name: 'Предприниматель',
        gender: 'male',
        club: 'scientific',
        tarot: 'pentacles', // масть
        psychotype: 'victim', // группа
        populationPercentage: '2 — 5%',
        aspects: {
            good: 'business',
            necessary: 'time',
            bad: 'logic',
            noNeed: 'ideas',
            fear: 'emotions',
            problems: 'comfort',
            desires: 'people',
            solutions: 'will',
        },
        stimulant: 'uniqueness',
        communication: 'business',
        companion: 'stubborn',
        temperament: 'choleric',
        ideology: 'neutralBad',
        jungs: [
            'intuit',
            'logic',
            'extravert',
            'rational',
        ],
        reinin: [
            'dynamic',
            'positivist',
            'declamtim',
            'strategist',
            'emotivist',

            'result',
            'compliant',
            'careless',

            'decisive',
            'objective',
            'democrat',
        ],
    },

    ESTJ: {
        element: 'earth',
        role: 'king',
        alias: 'Штирлиц',
        mindKey: 'rational-4',
        mind: 'algorithmic',
        name: 'Администратор',
        gender: 'male',
        club: 'practice',
        tarot: 'pentacles', // масть
        psychotype: 'care', // группа
        populationPercentage: '8 — 12%',
        aspects: {
            good: 'business',
            necessary: 'comfort',
            bad: 'logic',
            noNeed: 'will',
            fear: 'emotions',
            problems: 'time',
            desires: 'people',
            solutions: 'ideas',
        },
        stimulant: 'status',
        communication: 'business',
        companion: 'stubborn',
        temperament: 'choleric',
        ideology: 'lawAbidingBad',
        jungs: [
            'sensoric',
            'logic',
            'extravert',
            'rational',
        ],
        reinin: [
            'dynamic',
            'negativist',
            'questim',
            'tactician',
            'emotivist',

            'process',
            'compliant',
            'provident',

            'reasonable',
            'objective',
            'aristocrat',
        ],
    },

    INFJ: {
        element: 'earth',
        role: 'paige',
        alias: 'Достоевский',
        mindKey: 'rational-1',
        mind: 'casual',
        name: 'Гуманист',
        gender: 'female',
        club: 'humanitarian',
        tarot: 'wands', // масть
        psychotype: 'infantile', // группа
        populationPercentage: '1 — 3%',
        aspects: {
            good: 'people',
            necessary: 'ideas',
            bad: 'emotions',
            noNeed: 'time',
            fear: 'logic',
            problems: 'will',
            desires: 'business',
            solutions: 'comfort',
        },
        stimulant: 'selfSufficiency',
        communication: 'coldBlooded',
        companion: 'provident',
        temperament: 'phlegmatic',
        ideology: 'neutralKindly',
        jungs: [
            'intuit',
            'etic',
            'introvert',
            'rational',
        ],
        reinin: [
            'static',
            'positivist',
            'declamtim',
            'strategist',
            'constructivist',

            'process',
            'compliant',
            'provident',

            'reasonable',
            'objective',
            'aristocrat',
        ],
    },

    ENFP: {
        element: 'earth',
        role: 'knight',
        alias: 'Гексли',
        mindKey: 'irrational-1',
        mind: 'holographic',
        name: 'Советчик',
        gender: 'male',
        club: 'humanitarian',
        tarot: 'cups', // масть
        psychotype: 'infantile', // группа
        populationPercentage: '6 — 8%',
        aspects: {
            good: 'ideas',
            necessary: 'people',
            bad: 'time',
            noNeed: 'emotions',
            fear: 'will',
            problems: 'logic',
            desires: 'comfort',
            solutions: 'business',
        },
        stimulant: 'uniqueness',
        communication: 'passionate',
        companion: 'uncompromising',
        temperament: 'sanguine',
        ideology: 'chaoticKindly',
        jungs: [
            'intuit',
            'etic',
            'extravert',
            'irrational',
        ],
        reinin: [
            'static',
            'negativist',
            'declamtim',
            'tactician',
            'emotivist',

            'result',
            'stubborn',
            'careless',

            'reasonable',
            'objective',
            'aristocrat',
        ],
    },

    ISTP: {
        element: 'earth',
        role: 'lady',
        alias: 'Габен',
        mindKey: 'irrational-1',
        mind: 'vortical',
        name: 'Мастер',
        gender: 'female',
        club: 'practice',
        tarot: 'swords', // масть
        psychotype: 'care', // группа
        populationPercentage: '4 — 6%',
        aspects: {
            good: 'comfort',
            necessary: 'business',
            bad: 'will',
            noNeed: 'logic',
            fear: 'time',
            problems: 'emotions',
            desires: 'ideas',
            solutions: 'people',
        },
        stimulant: 'welfare',
        communication: 'coldBlooded',
        companion: 'restrained',
        temperament: 'melancholic',
        ideology: 'neutral',
        jungs: [
            'sensoric',
            'logic',
            'introvert',
            'irrational',
        ],
        reinin: [
            'dynamic',
            'positivist',
            'questim',
            'strategist',
            'constructivist',

            'result',
            'stubborn',
            'careless',

            'reasonable',
            'objective',
            'aristocrat',
        ],
    },
};
