export const ROUTES = {
	HOME: '/',
	SOCIONICSTYPES: (id =':id') => `/socionics/type/${id}`,
	SOCIONICSTYPES_CARD: 'card',
	SOCIONICSTYPES_DESCRIPTION: 'description',
	SOCIONICSTYPES_COMPATIBILITY: 'compatibility',
	MENU: '/menu',
	DISCLAIMER: '/disclaimer',
	HISTORY: '/history',
	METABOLISM: '/information-metabolism',
	FUNCTIONS: '/functions',
	FUNCTIONS_ITEM: 'functions/:functionName',
	BLOCKS: '/blocks',
	BLOCK_ITEM: '/blocks/:blockName',
	ASPECTS: '/aspects',
	SUITS: '/suits',
	SUITS_CARD: (cardName = ':cardName') => `/suits/card/${cardName}`,
	SUITS_TAROT: (tarotName = ':tarotName') => `suits/tarot/${tarotName}`,
	QUADRAS: '/quadras',
	QUADRA_ITEM: (quadraName = ':quadraName') => `/quadra/${quadraName}`,
	INTERTYPE: '/intertype',
	INTERTYPE_ITEM: '/intertype/:id',
	MINDSETS: '/mindsets'
};